[debug] [2023-01-16T09:54:31.838Z] ----------------------------------------------------------------------
[debug] [2023-01-16T09:54:31.840Z] Command:       C:\Program Files\nodejs\node.exe C:\Users\raiha\AppData\Roaming\npm\node_modules\firebase-tools\lib\bin\firebase.js deploy
[debug] [2023-01-16T09:54:31.840Z] CLI Version:   11.19.0
[debug] [2023-01-16T09:54:31.840Z] Platform:      win32
[debug] [2023-01-16T09:54:31.840Z] Node Version:  v16.14.2
[debug] [2023-01-16T09:54:31.846Z] Time:          Mon Jan 16 2023 15:54:31 GMT+0600 (Bangladesh Standard Time)
[debug] [2023-01-16T09:54:31.846Z] ----------------------------------------------------------------------
[debug] 
[debug] [2023-01-16T09:54:31.850Z] >>> [apiv2][query] GET https://firebase-public.firebaseio.com/cli.json [none]
[debug] [2023-01-16T09:54:31.943Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[debug] [2023-01-16T09:54:31.944Z] > authorizing via signed-in user (sahadatblog13@gmail.com)
[debug] [2023-01-16T09:54:31.944Z] [iam] checking project chetona-client for permissions ["firebase.projects.get","firebasehosting.sites.update"]
[debug] [2023-01-16T09:54:31.945Z] > refreshing access token with scopes: []
[debug] [2023-01-16T09:54:31.946Z] >>> [apiv2][query] POST https://www.googleapis.com/oauth2/v3/token [none]
[debug] [2023-01-16T09:54:31.946Z] >>> [apiv2][body] POST https://www.googleapis.com/oauth2/v3/token [omitted]
[debug] [2023-01-16T09:54:32.359Z] <<< [apiv2][status] POST https://www.googleapis.com/oauth2/v3/token 200
[debug] [2023-01-16T09:54:32.359Z] <<< [apiv2][body] POST https://www.googleapis.com/oauth2/v3/token [omitted]
[debug] [2023-01-16T09:54:32.377Z] >>> [apiv2][query] POST https://cloudresourcemanager.googleapis.com/v1/projects/chetona-client:testIamPermissions [none]
[debug] [2023-01-16T09:54:32.377Z] >>> [apiv2][(partial)header] POST https://cloudresourcemanager.googleapis.com/v1/projects/chetona-client:testIamPermissions x-goog-quota-user=projects/chetona-client
[debug] [2023-01-16T09:54:32.377Z] >>> [apiv2][body] POST https://cloudresourcemanager.googleapis.com/v1/projects/chetona-client:testIamPermissions {"permissions":["firebase.projects.get","firebasehosting.sites.update"]}
[debug] [2023-01-16T09:54:32.640Z] <<< [apiv2][status] GET https://firebase-public.firebaseio.com/cli.json 200
[debug] [2023-01-16T09:54:32.640Z] <<< [apiv2][body] GET https://firebase-public.firebaseio.com/cli.json {"cloudBuildErrorAfter":1594252800000,"cloudBuildWarnAfter":1590019200000,"defaultNode10After":1594252800000,"minVersion":"3.0.5","node8DeploysDisabledAfter":1613390400000,"node8RuntimeDisabledAfter":1615809600000,"node8WarnAfter":1600128000000}
[debug] [2023-01-16T09:54:34.292Z] <<< [apiv2][status] POST https://cloudresourcemanager.googleapis.com/v1/projects/chetona-client:testIamPermissions 200
[debug] [2023-01-16T09:54:34.292Z] <<< [apiv2][body] POST https://cloudresourcemanager.googleapis.com/v1/projects/chetona-client:testIamPermissions {}
[debug] [2023-01-16T09:54:34.293Z] [iam] error while checking permissions, command may fail: FirebaseError: Authorization failed. This account is missing the following required permissions on project chetona-client:

  firebase.projects.get
  firebasehosting.sites.update
[debug] [2023-01-16T09:54:34.294Z] >>> [apiv2][query] GET https://firebase.googleapis.com/v1beta1/projects/chetona-client [none]
[debug] [2023-01-16T09:54:35.149Z] <<< [apiv2][status] GET https://firebase.googleapis.com/v1beta1/projects/chetona-client 403
[debug] [2023-01-16T09:54:35.149Z] <<< [apiv2][body] GET https://firebase.googleapis.com/v1beta1/projects/chetona-client {"error":{"code":403,"message":"The caller does not have permission","status":"PERMISSION_DENIED"}}
[debug] [2023-01-16T09:54:35.151Z] HTTP Error: 403, The caller does not have permission
[debug] [2023-01-16T09:54:35.631Z] FirebaseError: HTTP Error: 403, The caller does not have permission
    at responseToError (C:\Users\raiha\AppData\Roaming\npm\node_modules\firebase-tools\lib\responseToError.js:49:12)
    at RetryOperation._fn (C:\Users\raiha\AppData\Roaming\npm\node_modules\firebase-tools\lib\apiv2.js:288:77)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
[error] 
[error] Error: Failed to get Firebase project chetona-client. Please make sure the project exists and your account has permission to access it.
